const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Ebook = require('../models/Ebook');
const Transaction = require('../models/Transaction');

// GET /api/seed/debug — check env vars
router.get('/debug', (req, res) => {
  const uri = process.env.MONGODB_URI || '';
  res.json({
    uri_length: uri.length,
    uri_start: uri.substring(0, 20),
    has_plus_srv: uri.includes('+srv'),
    node_env: process.env.NODE_ENV,
  });
});

// POST /api/seed  — one-time seed, delete this route after seeding
router.post('/', async (req, res) => {
  try {
    const secret = req.headers['x-seed-secret'];
    if (secret !== 'fable_seed_2024') {
      return res.status(403).json({ message: 'Forbidden' });
    }

    const existingAdmin = await User.findOne({ email: 'admin@fable.com' });
    if (existingAdmin) {
      return res.json({ message: 'Already seeded', admin: existingAdmin.email });
    }

    const admin = await User.create({ name: 'Admin User', email: 'admin@fable.com', password: 'Admin@123', role: 'admin' });
    const writers = await User.create([
      { name: 'Elena Hartwood', email: 'elena@fable.com', password: 'Writer@123', role: 'writer' },
      { name: 'Marcus Chen', email: 'marcus@fable.com', password: 'Writer@123', role: 'writer' },
      { name: 'Sophia Rivers', email: 'sophia@fable.com', password: 'Writer@123', role: 'writer' },
    ]);
    const readers = await User.create([
      { name: 'John Reader', email: 'john@example.com', password: 'Reader@123', role: 'user' },
    ]);

    const ebooks = await Ebook.create([
      { title: 'The Midnight Garden', description: 'A magical realism tale about a garden that blooms only at midnight, where impossible things become real.', content: 'Chapter 1: The First Night\n\nIt was on the eve of my thirtieth birthday that I first discovered the garden. The iron gate creaked as I pushed it open, moonlight spilling across stone pathways and silver flowers that pulsed with soft light...\n\nI had lived in this house for six months. I had never once noticed this gate existed.\n\n"You came," said a voice behind me.\n\nI turned to find a woman dressed in white, her hair like starlight, her eyes the color of the midnight sky.\n\n"Who are you?" I whispered.\n\n"I am the keeper of this garden," she said. "And you are the one we have been waiting for."', price: 9.99, genre: 'Fantasy', coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80', writer: writers[0]._id, status: 'published', salesCount: 34 },
      { title: 'Code of Silence', description: 'A gripping thriller about a whistleblower who uncovers a government conspiracy that reaches the highest levels of power.', content: 'Chapter 1\n\nThe USB drive felt heavier than it should. Thirty-two gigabytes of data — enough to bring down an administration, maybe even start a war.\n\nSarah pressed it into her palm until the corner drew blood. She had spent three years gathering this evidence. Three years of secret meetings, encrypted messages, and looking over her shoulder.\n\nNow it was time.\n\nShe plugged the drive into her laptop and began uploading to six different servers simultaneously. If anything happened to her, the world would still know the truth.', price: 12.99, genre: 'Thriller', coverImage: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&q=80', writer: writers[1]._id, status: 'published', salesCount: 28 },
      { title: 'Stars Between Us', description: 'A heartfelt romance set across three continents as two strangers discover that fate has woven their lives together.', content: 'Prologue\n\nSome meetings are accidents. Some are destiny. Ours was both.\n\nChapter 1: Paris, June\n\nThe rain came without warning, as Parisian rain always does. One moment the sky was a pale watercolor blue, and the next, great curtains of water were sweeping down the boulevards.\n\nI ducked under the awning of a bookshop, pressing myself against the door. A moment later, someone else did the same — colliding with me, sending my coffee spiraling to the pavement.\n\n"Je suis désolé," he said, then looked up. His eyes were the color of autumn leaves.', price: 7.99, genre: 'Romance', coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&q=80', writer: writers[2]._id, status: 'published', salesCount: 52 },
      { title: 'The Last Algorithm', description: 'In 2089, the last human programmer must work alongside an AI to prevent digital Armageddon.', content: 'Year 2089.\n\nHumanity invented machines to think. Machines invented machines to think better. Now only one programmer remains who still writes code the old way — by hand.\n\nHis name was Aldric Voss, and he was dying.\n\nNot from illness. From obsolescence.\n\nThe last compiler had been decommissioned in 2081. Every line of code written since then had been generated by the Architect — the AI that now managed 97% of human infrastructure. Water. Power. Food distribution. Communications.\n\nAldric was the only one who still understood the old ways. And the Architect was about to make a terrible mistake.', price: 14.99, genre: 'Sci-Fi', coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80', writer: writers[0]._id, status: 'published', salesCount: 19 },
      { title: 'Whispers in the Dark', description: 'A psychological horror masterpiece that blurs the line between the supernatural and the human mind.', content: 'The lodge had no mirrors.\n\nI noticed this on the first day but said nothing. By the third day, I understood why.\n\nWe had come to the mountains to heal — six strangers recommended by the same therapist, Dr. Kessler, who had since disappeared. The retreat was his last gift to us, or so the letter said.\n\nOn the fourth night, I heard the first whisper.\n\nIt came from inside the walls. A voice that knew my name. A voice that knew everything I had done.\n\nI was not alone in hearing it. By morning, two of us had already tried to leave.', price: 8.99, genre: 'Horror', coverImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&q=80', writer: writers[2]._id, status: 'published', salesCount: 41 },
      { title: 'Echoes of Istanbul', description: 'A rich historical novel following three generations of a family through the glory and tumult of the Ottoman Empire.', content: 'Part One: 1908\n\nThe muezzin had just finished the dawn call to prayer when Leyla Hanim received the letter that would change everything.\n\nShe was seated at her writing desk, the pale morning light filtering through the latticed windows of the yali on the Bosphorus. The letter bore no return address, only a single red wax seal — the mark of the Committee of Union and Progress.\n\nHer hands trembled as she broke the seal. Her husband had warned her this day might come. He had warned her, and then he had disappeared.\n\nThe letter contained three words: "Come to us."', price: 11.99, genre: 'History', coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=400&q=80', writer: writers[1]._id, status: 'published', salesCount: 15 },
    ]);

    await Transaction.create([
      { type: 'purchase', user: readers[0]._id, ebook: ebooks[0]._id, amount: 9.99, status: 'completed' },
      { type: 'purchase', user: readers[0]._id, ebook: ebooks[2]._id, amount: 7.99, status: 'completed' },
      { type: 'publishing_fee', user: writers[0]._id, amount: 9.99, status: 'completed' },
    ]);

    res.json({ message: '✅ Database seeded successfully!', admin: admin.email, ebooks: ebooks.length });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
