const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Ebook = require('../models/Ebook');
const Transaction = require('../models/Transaction');

// GET /api/seed/debug — check env vars
router.get('/debug', (req, res) => {
  const uri = process.env.MONGODB_URI || '';
  res.json({
    uri_length: uri.length,
    uri_start: uri.substring(0, 20),
    has_plus_srv: uri.includes('+srv'),
    node_env: process.env.NODE_ENV,
  });
});

// POST /api/seed  — one-time seed, delete this route after seeding
router.post('/', async (req, res) => {
  try {
    const secret = req.headers['x-seed-secret'];
    if (secret !== 'fable_seed_2024') {
      return res.status(403).json({ message: 'Forbidden' });
    }

    const existingAdmin = await User.findOne({ email: 'admin@fable.com' });
    if (existingAdmin) {
      return res.json({ message: 'Already seeded', admin: existingAdmin.email });
    }

    const admin = await User.create({ name: 'Admin User', email: 'admin@fable.com', password: 'Admin@123', role: 'admin' });
    const writers = await User.create([
      { name: 'Elena Hartwood', email: 'elena@fable.com', password: 'Writer@123', role: 'writer' },
      { name: 'Marcus Chen', email: 'marcus@fable.com', password: 'Writer@123', role: 'writer' },
      { name: 'Sophia Rivers', email: 'sophia@fable.com', password: 'Writer@123', role: 'writer' },
    ]);
    const readers = await User.create([
      { name: 'John Reader', email: 'john@example.com', password: 'Reader@123', role: 'user' },
    ]);

    const ebooks = await Ebook.create([
      { title: 'The Midnight Garden', description: 'A magical realism tale about a garden that blooms only at midnight, where impossible things become real.', content: 'Chapter 1: The First Night\n\nIt was on the eve of my thirtieth birthday that I first discovered the garden. The iron gate creaked as I pushed it open, moonlight spilling across stone pathways and silver flowers that pulsed with soft light...\n\nI had lived in this house for six months. I had never once noticed this gate existed.\n\n"You came," said a voice behind me.\n\nI turned to find a woman dressed in white, her hair like starlight, her eyes the color of the midnight sky.\n\n"Who are you?" I whispered.\n\n"I am the keeper of this garden," she said. "And you are the one we have been waiting for."', price: 9.99, genre: 'Fantasy', coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80', writer: writers[0]._id, status: 'published', salesCount: 34 },
      { title: 'Code of Silence', description: 'A gripping thriller about a whistleblower who uncovers a government conspiracy that reaches the highest levels of power.', content: 'Chapter 1\n\nThe USB drive felt heavier than it should. Thirty-two gigabytes of data — enough to bring down an administration, maybe even start a war.\n\nSarah pressed it into her palm until the corner drew blood. She had spent three years gathering this evidence. Three years of secret meetings, encrypted messages, and looking over her shoulder.\n\nNow it was time.\n\nShe plugged the drive into her laptop and began uploading to six different servers simultaneously. If anything happened to her, the world would still know the truth.', price: 12.99, genre: 'Thriller', coverImage: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&q=80', writer: writers[1]._id, status: 'published', salesCount: 28 },
      { title: 'Stars Between Us', description: 'A heartfelt romance set across three continents as two strangers discover that fate has woven their lives together.', content: 'Prologue\n\nSome meetings are accidents. Some are destiny. Ours was both.\n\nChapter 1: Paris, June\n\nThe rain came without warning, as Parisian rain always does. One moment the sky was a pale watercolor blue, and the next, great curtains of water were sweeping down the boulevards.\n\nI ducked under the awning of a bookshop, pressing myself against the door. A moment later, someone else did the same — colliding with me, sending my coffee spiraling to the pavement.\n\n"Je suis désolé," he said, then looked up. His eyes were the color of autumn leaves.', price: 7.99, genre: 'Romance', coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&q=80', writer: writers[2]._id, status: 'published', salesCount: 52 },
      { title: 'The Last Algorithm', description: 'In 2089, the last human programmer must work alongside an AI to prevent digital Armageddon.', content: 'Year 2089.\n\nHumanity invented machines to think. Machines invented machines to think better. Now only one programmer remains who still writes code the old way — by hand.\n\nHis name was Aldric Voss, and he was dying.\n\nNot from illness. From obsolescence.\n\nThe last compiler had been decommissioned in 2081. Every line of code written since then had been generated by the Architect — the AI that now managed 97% of human infrastructure. Water. Power. Food distribution. Communications.\n\nAldric was the only one who still understood the old ways. And the Architect was about to make a terrible mistake.', price: 14.99, genre: 'Sci-Fi', coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80', writer: writers[0]._id, status: 'published', salesCount: 19 },
      { title: 'Whispers in the Dark', description: 'A psychological horror masterpiece that blurs the line between the supernatural and the human mind.', content: 'The lodge had no mirrors.\n\nI noticed this on the first day but said nothing. By the third day, I understood why.\n\nWe had come to the mountains to heal — six strangers recommended by the same therapist, Dr. Kessler, who had since disappeared. The retreat was his last gift to us, or so the letter said.\n\nOn the fourth night, I heard the first whisper.\n\nIt came from inside the walls. A voice that knew my name. A voice that knew everything I had done.\n\nI was not alone in hearing it. By morning, two of us had already tried to leave.', price: 8.99, genre: 'Horror', coverImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&q=80', writer: writers[2]._id, status: 'published', salesCount: 41 },
      { title: 'Echoes of Istanbul', description: 'A rich historical novel following three generations of a family through the glory and tumult of the Ottoman Empire.', content: 'Part One: 1908\n\nThe muezzin had just finished the dawn call to prayer when Leyla Hanim received the letter that would change everything.\n\nShe was seated at her writing desk, the pale morning light filtering through the latticed windows of the yali on the Bosphorus. The letter bore no return address, only a single red wax seal — the mark of the Committee of Union and Progress.\n\nHer hands trembled as she broke the seal. Her husband had warned her this day might come. He had warned her, and then he had disappeared.\n\nThe letter contained three words: "Come to us."', price: 11.99, genre: 'History', coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=400&q=80', writer: writers[1]._id, status: 'published', salesCount: 15 },
    ]);

    await Transaction.create([
      { type: 'purchase', user: readers[0]._id, ebook: ebooks[0]._id, amount: 9.99, status: 'completed' },
      { type: 'purchase', user: readers[0]._id, ebook: ebooks[2]._id, amount: 7.99, status: 'completed' },
      { type: 'publishing_fee', user: writers[0]._id, amount: 9.99, status: 'completed' },
    ]);

    res.json({ message: '✅ Database seeded successfully!', admin: admin.email, ebooks: ebooks.length });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST /api/seed/fix — remove duplicates and fix broken images
router.post('/fix', async (req, res) => {
  try {
    const secret = req.headers['x-seed-secret'];
    if (secret !== 'fable_seed_2024') return res.status(403).json({ message: 'Forbidden' });

    // Remove duplicates — keep only the one with highest salesCount per title
    const all = await Ebook.find({}).lean();
    const seen = {};
    const toDelete = [];
    for (const eb of all) {
      const key = eb.title.toLowerCase().trim();
      if (seen[key]) {
        // Keep the one with higher salesCount, delete the other
        if ((eb.salesCount || 0) >= (seen[key].salesCount || 0)) {
          toDelete.push(seen[key]._id);
          seen[key] = eb;
        } else {
          toDelete.push(eb._id);
        }
      } else {
        seen[key] = eb;
      }
    }
    if (toDelete.length) await Ebook.deleteMany({ _id: { $in: toDelete } });

    // Fix ALL broken/duplicate cover images — each title gets a unique, genre-appropriate photo
    const fixes = [
      // Blank / broken
      { title: 'Dead Letters',         img: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&q=80' }, // handwritten letters
      // Duplicate: clown horror image reused on mystery books
      { title: 'The Vanishing Hour',   img: 'https://images.unsplash.com/photo-1475274047050-1d0c0975c63e?w=400&q=80' }, // foggy night road
      // Duplicate: romance hero bg reused on book
      { title: 'When We First Met',    img: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=400&q=80' }, // romantic dinner
      // Duplicate: sci-fi bg reused on book
      { title: 'The Quantum Garden',   img: 'https://images.unsplash.com/photo-1488841714725-bb4c32d1ac94?w=400&q=80' }, // exotic alien plants
      // Duplicate: Midnight Garden fantasy image reused on dragon book
      { title: "The Dragon's Keep",    img: 'https://images.unsplash.com/photo-1501084817266-d5a88b0b9e0e?w=400&q=80' }, // dark fantasy landscape
      // Duplicate: horror bg reused on book
      { title: 'The Hollow House',     img: 'https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?w=400&q=80' }, // dark empty corridor
      // Duplicate: Echoes of Istanbul history image reused
      { title: 'Silk Road Chronicles', img: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=400&q=80' },   // colorful spice market
      // Duplicate: Code of Silence thriller image reused
      { title: 'The Final Witness',    img: 'https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?w=400&q=80' }, // dark political scene
      // Duplicate: adventure bg reused on book
      { title: 'The Lost Expedition',  img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80' }, // snowy Patagonia
      // Previously identified fixes (keep them)
      { title: 'Crown of Shadows',     img: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80' },
      { title: "The Mage's Bargain",   img: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&q=80' },
      { title: 'The Summer Villa',     img: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=400&q=80' },
    ];
    let fixed = 0;
    for (const f of fixes) {
      const updated = await Ebook.updateOne(
        { title: f.title },
        { $set: { coverImage: f.img } }
      );
      if (updated.modifiedCount) fixed++;
    }

    res.json({ message: '✅ Fixed!', duplicatesRemoved: toDelete.length, imagesFixed: fixed });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST /api/seed/more-ebooks — add 30 more ebooks to existing writers
router.post('/more-ebooks', async (req, res) => {
  try {
    const secret = req.headers['x-seed-secret'];
    if (secret !== 'fable_seed_2024') return res.status(403).json({ message: 'Forbidden' });

    const elena = await User.findOne({ email: 'elena@fable.com' });
    const marcus = await User.findOne({ email: 'marcus@fable.com' });
    const sophia = await User.findOne({ email: 'sophia@fable.com' });
    if (!elena || !marcus || !sophia) return res.status(400).json({ message: 'Writers not found — run /api/seed first' });

    const existing = await Ebook.countDocuments();
    if (existing >= 30) return res.json({ message: 'More ebooks already seeded', count: existing });

    const newEbooks = await Ebook.create([
      // Fiction
      { title: 'The Glass House', description: 'A family harboring dark secrets lives in a glass house where nothing can be hidden — until the day everything shatters.', content: 'Chapter 1\n\nWe lived in a house made entirely of glass. My father designed it that way on purpose, he said. "No secrets between us," he would say, smiling at Mother across the breakfast table.\n\nBut I was seventeen when I understood the truth: the glass was not for honesty. It was for control.\n\nHe wanted to see us. Every moment. Every room. Every shadow we tried to hide in.\n\nThe summer it all broke apart began with a stranger walking up our gravel drive on a Tuesday morning in July, carrying a leather briefcase and a name none of us expected to hear again.', price: 10.99, genre: 'Fiction', coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80', writer: elena._id, status: 'published', salesCount: 44 },
      { title: 'Between the Lines', description: 'Two readers on opposite sides of the world exchange notes in the margins of a secondhand book — and fall in love.', content: 'I found the book at a market stall in Dublin on a grey Wednesday morning.\n\nIt was an old paperback copy of The Count of Monte Cristo, its spine cracked, its pages yellow at the edges. I almost put it back. Then I noticed the handwriting in the margins.\n\nSomeone had been annotating this book for years. The notes were in blue ink, then black, then red — different pens at different times. Furious arguments with the author. Tiny drawings. Jokes that made me laugh out loud in the middle of the market.\n\nAt the back, someone had written: "If you find this, I hope you loved it as much as I did. — J"\n\nI bought the book. I read it in three days. Then I wrote back.', price: 9.49, genre: 'Fiction', coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 37 },
      { title: 'A Quiet Revolution', description: 'In a small town in 1960s America, a librarian quietly changes lives one banned book at a time.', content: 'Chapter One\n\nThe first book Eleanor hid was The Catcher in the Rye. She slipped it behind a row of encyclopedias on a Monday morning, before the library opened, before Mayor Hollis could come with his list.\n\nHe arrived at nine sharp, as always, suit pressed, smile absent.\n\n"Mrs. Crane," he said. "I trust you\'ve received the updated prohibited titles list from the school board?"\n\n"I have, Mayor."\n\n"And you\'ve removed them all?"\n\n"I\'ve attended to the matter personally."\n\nHe looked around the library — the shelves, the reading tables, the children\'s corner — and nodded, satisfied.\n\nHe never thought to look behind the encyclopedias.', price: 8.99, genre: 'Fiction', coverImage: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 29 },
      // Mystery
      { title: 'The Vanishing Hour', description: 'Every year on the same date, someone disappears from the village of Dawnmere. Detective Iris Crane has exactly 24 hours to stop it.', content: 'March 14th. 11:58 PM.\n\nDetective Iris Crane stood in the rain outside the old mill, torch in hand, watching the second hand tick toward midnight.\n\nShe had read the files. Fourteen disappearances. Fourteen years. Always March 14th. Always someone between the ages of twenty and forty. Always a body — or the absence of one — found at dawn.\n\nThe village said it was a curse. The department said it was coincidence.\n\nIris said it was a killer who was very, very patient.\n\nThe clock struck midnight.\n\nSomewhere across the village, a light went out.', price: 11.49, genre: 'Mystery', coverImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&q=80', writer: elena._id, status: 'published', salesCount: 61 },
      { title: 'Dead Letters', description: 'A postal worker discovers that letters addressed to the dead are being answered — and the replies contain confessions to unsolved crimes.', content: 'The first letter came back on a Thursday.\n\nI\'d sorted mail for nineteen years. I knew every address on my route, knew which houses had dogs, which had teenagers who never checked the box. I knew the dead ones too — the names that lingered on the route long after the occupants were gone.\n\nMr. Harold Finch, 14 Birchwood Lane, had been dead for three years. His house had been sold, gutted, and resold. A young couple lived there now with a labrador named Biscuit.\n\nSo when I pulled a letter addressed to Mr. Harold Finch — in fresh ink, with today\'s postmark — and found a reply already waiting in the outgoing box, I did something I had never done before.\n\nI opened it.', price: 12.49, genre: 'Mystery', coverImage: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 33 },
      { title: 'The Blue Room', description: 'A forensic psychologist is called to assess a man claiming to be innocent — but he knows details only the killer could know.', content: 'Interview Room 4 had no windows. That was intentional. Dr. Mara Voss had requested it herself. Windows gave prisoners something to look at other than her. She needed their full attention.\n\nDaniel Ashford sat across the table, wrists unshackled at her request. Forty-two years old. Former architect. Convicted of three murders. IQ of 141.\n\n"You said you wanted to talk to someone who would listen," Mara said.\n\n"I said I wanted to talk to someone who would believe me."\n\n"I haven\'t decided that yet."\n\nHe smiled. It was not a frightening smile. That was the most frightening thing about it.\n\n"Ask me something only the killer would know," he said.', price: 13.99, genre: 'Mystery', coverImage: 'https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 48 },
      // Romance
      { title: 'When We First Met', description: 'Two childhood enemies are forced to plan their siblings\' wedding together — and rediscover why they really stopped talking.', content: 'I hadn\'t seen Leo Marchetti in seven years. The last words we had exchanged were not words I intended to repeat in polite company.\n\nAnd now his sister was marrying my brother.\n\nMy mother said this was destiny. I said it was a logistical nightmare. We were both right.\n\nHe arrived at the planning meeting twelve minutes late, carrying two coffees — one of which he handed to me without being asked, because he still remembered I took it black with one sugar, and that annoyed me more than anything.\n\n"Rosie," he said.\n\n"Leonardo," I said, because I knew he hated his full name.\n\nHe sat down across from me and smiled. "This is going to be fun."', price: 8.49, genre: 'Romance', coverImage: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400&q=80', writer: elena._id, status: 'published', salesCount: 72 },
      { title: 'The Summer Villa', description: 'A burned-out travel writer rents a Tuscan villa and finds herself falling for the farmer next door who doesn\'t own a smartphone.', content: 'The villa was perfect. The road to it was not.\n\nI had driven three kilometers down an unpaved track with a rental car that was approximately the size of a shoebox when the car made a sound it should not have made, lurched sideways, and died.\n\nI sat in silence for a moment, listening to crickets and the distant sound of someone laughing.\n\n"The track gets everyone," said a voice.\n\nI looked up. A man was leaning on a gate post, arms folded, watching me with an expression somewhere between sympathy and amusement. He had dirt on his hands and flour on his shirt and the kind of tan you only get from actually working outdoors, not lying on a sun lounger.\n\n"Do you have a phone I can borrow?" I asked.\n\n"No," he said.', price: 9.99, genre: 'Romance', coverImage: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 88 },
      { title: 'Love in Translation', description: 'A Korean translator and a Brazilian chef meet in Tokyo and must navigate language, culture, and distance to find each other.', content: 'There are forty-three ways to express loneliness in Korean. I know all of them.\n\nSoomin had been in Tokyo for eight months when she met the man who didn\'t speak Korean, or Japanese, or English with any particular fluency, but who handed her the exact item she had been pointing at for five minutes in the market with such ease that she forgot, momentarily, that communication was supposed to be difficult.\n\n"Obrigado," he said to the vendor, and then turned to her with a smile that required no translation.\n\nHis name was Rafael. He was making a documentary about street food. He had been in Tokyo for three weeks and had already learned to order four dishes and say good morning.\n\n"That\'s four more things than most people bother with," Soomin said.\n\n"I like learning," he said. "Especially when the teachers are interesting."', price: 10.49, genre: 'Romance', coverImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 56 },
      // Sci-Fi
      { title: 'Neon Horizon', description: 'In a city where memories can be bought and sold, a black-market memory dealer discovers a recording that should not exist.', content: '2071. Neo Cascadia.\n\nThey called it the Memory Market, though it had dozens of other names depending on who you asked and how much trouble they were willing to admit to being in.\n\nRex Tanaka had been selling memories for six years. Nostalgia was his specialty — sunsets, weddings, first days of school. Clean memories. Happy ones. The kind that aging executives paid a premium for when their own had started to blur.\n\nThe memory he found on a Tuesday morning in a dead drop beneath Platform Nine was none of those things.\n\nHe jacked in for a sample — two seconds maximum, just enough to verify the goods.\n\nHe came out shaking.\n\nThe memory was dated thirty years from now. And the person remembering it was him.', price: 13.49, genre: 'Sci-Fi', coverImage: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 67 },
      { title: 'The Quantum Garden', description: 'A botanist on a dying planet discovers a flower that exists in multiple timelines simultaneously — and the wrong choice could erase one of them.', content: 'The flower bloomed at midnight.\n\nDr. Yael Maris had been awake for thirty-one hours straight when she first saw it. She thought sleep deprivation was making her hallucinate.\n\nBut the instruments confirmed what her eyes were seeing: the flower existed in three places at once.\n\nNot three flowers. One flower. Three simultaneous locations. Three timelines overlapping at a single quantum point.\n\nShe named it Paradox Bloom. She knew immediately that she should destroy it.\n\nShe also knew, with absolute certainty, that she could not.', price: 15.99, genre: 'Sci-Fi', coverImage: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=400&q=80', writer: elena._id, status: 'published', salesCount: 41 },
      { title: 'Colony Zero', description: 'The first human colony on Mars faces an existential threat — not from the planet, but from Earth\'s decision to cut communications.', content: 'Day 847. Mars Colony Ares-1.\n\nThe silence came at 0347 hours, local time.\n\nCommander Petra Holst was in the hydroponic bay when every screen on the colony went dark simultaneously. She didn\'t panic. She was trained not to panic. She had spent four years being trained for exactly this.\n\nBut she had never been trained for a scenario where Earth simply stopped answering.\n\nNot static. Not equipment failure. Complete, deliberate silence.\n\nBy 0500, all 312 colonists were awake. By 0700, Petra had drafted the message she never expected to write:\n\n"We are declaring operational independence. We will survive. Message ends."', price: 14.49, genre: 'Sci-Fi', coverImage: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 39 },
      // Fantasy
      { title: "The Dragon's Keep", description: 'A young mapmaker is hired to chart the boundaries of a dragon\'s territory — and discovers the dragon has been waiting for her specifically.', content: 'No reputable cartographer agreed to map dragon territories. They were poorly paid, poorly defined, and the clients were almost universally deceased before the maps were delivered.\n\nCassidy was not a reputable cartographer.\n\nShe was twenty-three, in significant debt, and in possession of a commission bearing a seal she had never seen before — a dragon coiled around a compass rose, wings spread, eyes that seemed to follow her when she tilted the parchment.\n\nThe payment offered was enough to clear her debts three times over.\n\nShe accepted.\n\nShe arrived at the mountain on the first day of autumn to find the dragon already waiting.\n\n"You\'re shorter than I expected," the dragon said.', price: 11.99, genre: 'Fantasy', coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80', writer: elena._id, status: 'published', salesCount: 59 },
      { title: 'Crown of Shadows', description: 'When the shadow kingdom\'s heir vanishes, a reluctant soldier must navigate a court of lies to find a truth that could unmake two worlds.', content: 'The Shadow Crown had not been worn in three hundred years.\n\nCommander Lyra Ashveil found it sitting on the steps of the throne room at dawn, unattended, gleaming with the cold light that meant old magic. She had seen the old texts. She knew what the crown\'s appearance meant.\n\nThe heir was gone.\n\nAnd someone had placed the crown where she would be the first to find it.\n\nShe looked at the crown for a long time. She thought about rank, and duty, and the fact that she had spent fifteen years serving a kingdom that had never once asked her what she wanted.\n\nThen she picked it up.\n\nThe court would have questions. She had decided she would have answers.', price: 12.99, genre: 'Fantasy', coverImage: 'https://images.unsplash.com/photo-1551269901-5c5e5b2cc29d?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 53 },
      { title: "The Mage's Bargain", description: 'A street thief accidentally steals a spell from the most powerful mage in the city — and must work off the debt in ways neither expected.', content: 'The rule in Thornwick was simple: steal from merchants, never from mages.\n\nSeven had been following this rule successfully for four years. One lapse of attention, one unlocked door, one room that looked from the outside like an apothecary storage space, and suddenly she was standing in a chamber full of bottled light with a spell she\'d palmed purely by reflex fizzing against her skin.\n\nThe mage appeared from nowhere.\n\nOld. Tall. Deeply unimpressed.\n\n"Put that back," he said.\n\nShe tried. The spell had already bonded.\n\n"Ah," said the mage. His expression shifted from annoyed to calculating. "Well. This is inconvenient for both of us. We had better come to an arrangement."', price: 10.99, genre: 'Fantasy', coverImage: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 47 },
      // Horror
      { title: 'The Hollow House', description: 'A sound engineer moves into a century-old house and begins recording ambient noise — only to find voices in the silence.', content: 'I bought the recorder to document silence.\n\nThat sounds strange, I know. But silence has texture — the silence of a cathedral is different from the silence of a forest, different again from the silence of an empty house. I\'d been building a library of silences for three years.\n\nThe house on Vane Street had been empty for eleven years. The landlord was transparent about this. He showed me the history, the surveys, the structural reports. He did not mention the sounds.\n\nI discovered those myself, on the third night, when I played back my recordings and heard, buried beneath the hiss of an empty room, a voice saying my name.\n\nI had been alone in the house when I recorded it.\n\nI was still alone. I was almost certain.', price: 9.99, genre: 'Horror', coverImage: 'https://images.unsplash.com/photo-1520116468816-95b69f847357?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 58 },
      { title: 'Dark Waters', description: 'A marine biologist\'s deep-sea expedition goes wrong when they realize the bioluminescent organisms they\'re studying are trying to communicate.', content: 'At three thousand meters below the surface, there is no light that belongs to the sun.\n\nDr. Nora Calloway had made this dive fourteen times. She knew the darkness, the pressure, the way sound traveled differently down here. She knew the creatures — the viperfish, the anglerfish, the things with no names that science had not yet categorized.\n\nShe did not know what she was looking at now.\n\nThe bioluminescence spread in patterns. Not random blooming, not defensive flash. Patterns that repeated. Patterns with intervals. Patterns that changed when she moved the submersible\'s light.\n\nThey were responding.\n\nShe turned on the recording equipment with hands that were absolutely steady.\n\n"Day fourteen," she said. "Contact established."', price: 11.49, genre: 'Horror', coverImage: 'https://images.unsplash.com/photo-1559825481-12a05cc00344?w=400&q=80', writer: elena._id, status: 'published', salesCount: 36 },
      { title: 'The Visitor', description: 'After a near-death experience, a woman begins seeing a figure in every photograph ever taken of her — standing just behind her, smiling.', content: 'The doctors said I was lucky.\n\nFifteen seconds without a heartbeat. Fifteen seconds, they said, was nothing. People came back from longer.\n\nI came back changed.\n\nI didn\'t realize this at first. I felt normal. I went home, rested, went back to work. Two weeks passed.\n\nThen my sister sent me a folder of old family photos she\'d been digitizing.\n\nI opened the first one: my seventh birthday. I\'m blowing out candles. My family is gathered around.\n\nAnd standing directly behind me, slightly out of focus but unmistakably there, is a figure I do not recognize.\n\nSmiling.\n\nI opened the next photo. Different year. Same figure.\n\nI went back thirty years. They were there in every one.', price: 10.49, genre: 'Horror', coverImage: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 64 },
      // Biography
      { title: 'Unbroken Spirit', description: 'The inspiring true-style story of a refugee who became a surgeon, told through letters written to the country she left behind.', content: 'Letter One\n\nDear Country I Can No Longer Name,\n\nI am writing this from a hospital in Birmingham, England. It is 2:17 in the morning. I have just finished a twelve-hour surgery and I am eating a sandwich from a vending machine and thinking about the river we crossed when I was nine.\n\nI wonder sometimes if you know where I ended up. I wonder if borders have memories.\n\nI am a surgeon now. A real one, with certificates on the wall and a white coat that actually fits. When I tell my colleagues I once crossed a river on an inflatable mattress with my mother and my brother and forty strangers, they don\'t know what to say.\n\nI\'ve stopped minding.\n\nI wanted to write this down before I forgot any of it. Before success softened the edges of difficulty the way it tends to.', price: 13.99, genre: 'Biography', coverImage: 'https://images.unsplash.com/photo-1502101872923-d48509bff386?w=400&q=80', writer: elena._id, status: 'published', salesCount: 45 },
      { title: 'The Road to Tomorrow', description: 'A first-generation college graduate documents the five years it took to change his family\'s trajectory — one decision at a time.', content: 'I was the first person in my family to sit in a college classroom.\n\nNot the first to want to. My mother had wanted it. Her mother before her. But wanting and getting are separated by money, and timing, and the kind of luck that passes some families over for generations.\n\nI got in on a Tuesday. I sat in the parking lot of the community college and looked at the acceptance letter for forty minutes before I called my mother.\n\nShe cried. I pretended not to.\n\nThis is the story of those four years, and the year before them, and the year after. It is the story of what you have to become to get somewhere your family has never been. It is the story of what you risk losing when you do.\n\nIt is also the story of what you find.', price: 12.49, genre: 'Biography', coverImage: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 31 },
      // Self-Help
      { title: 'Master Your Mind', description: 'A neuroscientist\'s practical guide to rewiring your thought patterns for clarity, focus, and sustainable motivation.', content: 'Introduction: The 90-Second Rule\n\nHere is something most productivity books won\'t tell you: the emotion you\'re feeling right now will pass in ninety seconds if you let it.\n\nNeuroscientist Jill Bolte Taylor identified this: the physiological response to any emotion — fear, anger, grief — lasts approximately ninety seconds in the brain. What keeps it going beyond that is thought. The stories we tell ourselves. The loops we run.\n\nThis book is about interrupting those loops.\n\nNot through willpower. Not through motivation. Through understanding the actual mechanisms behind how your brain processes experience — and using that understanding to make deliberate choices about what you do next.\n\nYou don\'t have to be a neuroscientist to use this. You just have to be willing to be curious about your own mind.', price: 14.99, genre: 'Self-Help', coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 93 },
      { title: 'The Focus Code', description: 'How to build deep concentration in the age of infinite distraction — a system used by world-class performers.', content: 'Chapter 1: The Attention Economy\n\nEvery app on your phone was designed by a team of engineers whose sole job was to make you unable to put it down.\n\nI don\'t say this to alarm you. I say it because it\'s important to understand what you\'re up against.\n\nDeep focus — the ability to concentrate without distraction on a cognitively demanding task — is becoming increasingly rare. And because it\'s rare, it\'s becoming increasingly valuable. The people who can do it are the people who produce extraordinary work.\n\nYou can be one of them.\n\nThis book is not about quitting technology. It\'s about using it on your terms, not its terms. It\'s about building a relationship with your attention that treats it as the finite, precious resource it actually is.\n\nLet\'s start there.', price: 13.49, genre: 'Self-Help', coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 78 },
      // History
      { title: 'The Hidden War', description: 'The untold stories of female resistance fighters in WWII-occupied France, reconstructed from recovered diaries and encoded letters.', content: 'Prologue\n\nThis book began with a suitcase.\n\nIn 2019, during the renovation of a farmhouse in the Dordogne region of France, workers discovered a metal suitcase bricked into a cellar wall. Inside were forty-seven handwritten notebooks, three rolls of undeveloped film, and a bundle of letters written in code.\n\nThe suitcase had been placed there in August 1944.\n\nThe woman who placed it had gone by six different names. The Resistance knew her as "Sparrow." Her real name was Celeste Arnaud. She was twenty-six years old when the war ended. She never spoke publicly about what she had done.\n\nThe notebooks spoke for her.', price: 15.49, genre: 'History', coverImage: 'https://images.unsplash.com/photo-1461360228754-6e81c478b882?w=400&q=80', writer: elena._id, status: 'published', salesCount: 42 },
      { title: 'Silk Road Chronicles', description: 'A vivid account of the merchants, monks, and diplomats who shaped the ancient trade routes connecting East and West.', content: 'In 100 BC, a Roman citizen could eat pepper from India on bread made from Egyptian wheat while wearing silk from China, without knowing the name of any country that produced these things.\n\nThis was the Silk Road.\n\nNot a single road — never a single road — but a shifting web of paths, passes, river routes, and sea lanes that connected the Mediterranean world to Central Asia, South Asia, and the Far East for over a thousand years.\n\nWhat moved along these routes was not only silk. It was ideas. Religions. Diseases. Technologies. Languages. Art forms. Mathematical concepts. Musical instruments.\n\nThis is the story of the people who walked those roads and what they carried with them.', price: 16.99, genre: 'History', coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 27 },
      // Poetry
      { title: 'Scattered Light', description: 'A debut poetry collection exploring grief, memory, and the slow return to joy through the language of light and seasons.', content: 'I.\n\nGrief does not arrive like a storm.\nIt arrives like fog — slowly,\nuntil you cannot see your hands\nin front of you\nand you have forgotten\nthat there was ever a morning\nwithout it.\n\nII.\n\nThe first season without her\nI watched the leaves fall\nand thought about how she used to say\nthey were letting go on purpose.\n\nShe was always better at metaphors\nthan I was.\n\nIII.\n\nSomewhere in February\nI found myself laughing at something\nbefore I remembered.\n\nI stood with the laugh still in my chest,\nnot knowing whether to be grateful\nor ashamed.\n\nI chose grateful.\nI think she would have wanted that.', price: 7.99, genre: 'Poetry', coverImage: 'https://images.unsplash.com/photo-1499244571948-7ccddb3583f1?w=400&q=80', writer: elena._id, status: 'published', salesCount: 22 },
      { title: 'City Songs', description: 'Poems written on commutes, in coffee shops, and under bridges — a love letter to urban solitude and unexpected connection.', content: 'Subway, 8:47 AM\n\nWe are packed in\nlike pages in a book,\nspines touching,\nstories never meeting.\n\nThe man beside me\nis crying very quietly.\nHe thinks no one can tell.\nWe all can tell.\nWe all look away.\nThis is the kindness we know how to give.\n\n—\n\nCoffee Shop, 2 PM\n\nShe has been writing\nthe same sentence\nfor forty minutes.\n\nI recognize this.\nI do not interrupt.\n\nSome sentences need\nto be almost written\nbefore they can be written.\n\n—\n\nPark Bench, Dusk\n\nThe pigeons have opinions\nabout the crumbs\nbut settle, eventually,\nfor what they are given.\n\nI think about this more\nthan I probably should.', price: 6.99, genre: 'Poetry', coverImage: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 19 },
      // Thriller
      { title: 'The Final Witness', description: 'The only witness to a political assassination wakes from a coma with no memory — and someone will kill to keep it that way.', content: 'The woman in Room 7 had been unconscious for nineteen days.\n\nShe had no ID. No phone. No jewelry. The clothes she\'d been wearing when she was brought in — a grey coat, jeans, one missing shoe — had no labels, no identifying marks.\n\nThe police had processed her as a Jane Doe and moved on. People disappeared in this city. Most of them wanted to.\n\nDetective Yusuf Adeyemi had not moved on. He had watched the security footage from the street where she was found forty-seven times. He had tracked the crowds. He had counted backward from the moment she collapsed.\n\nShe had been three blocks from the senator\'s motorcade at the exact moment of the assassination.\n\nThen she had started walking in the wrong direction.\n\nThen she had stopped walking entirely.\n\nNow she was waking up.', price: 12.99, genre: 'Thriller', coverImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 74 },
      { title: 'Shadow Protocol', description: 'A cyber-security analyst realizes the system she built to protect civilians has been turned into the world\'s most sophisticated surveillance weapon.', content: 'ARIA had been designed to protect.\n\nI had built her over four years — four years of late nights, cold coffee, arguments with the ethics board, and the quiet, deep satisfaction of watching something work. ARIA was the most sophisticated threat-detection system ever deployed by a civilian government. She could identify patterns, flag anomalies, protect infrastructure. She was elegant. She was precise. She was mine.\n\nShe was also, I understood on a Tuesday morning at 6:43 AM while reviewing a routine report, watching approximately forty million people who had never been accused of anything.\n\nNot protecting them. Watching them.\n\nI stared at the data for a long time.\n\nThen I began to understand what I had actually built.', price: 13.99, genre: 'Thriller', coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=80', writer: elena._id, status: 'published', salesCount: 66 },
      // Adventure
      { title: 'Into the Unknown', description: 'A disgraced explorer leads a ragtag team into the Amazon to find a lost civilization — and must confront what she\'s been running from.', content: 'The last expedition had cost three lives. Mine, technically, was almost one of them.\n\nI\'d been back in London for seven months when the photograph arrived. No return address. Just an image, slightly blurred, taken with a long lens in difficult light.\n\nA stone structure. Unmistakably carved. Unmistakably human. In the middle of a section of the Amazon that, according to every map and satellite survey ever conducted, contained nothing but canopy and river.\n\nI knew what it meant.\n\nI also knew that funding a new expedition after what happened in 2019 would require either a miracle or a very rich person with questionable judgment.\n\nAs it turned out, it required both.', price: 11.99, genre: 'Adventure', coverImage: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=400&q=80', writer: marcus._id, status: 'published', salesCount: 55 },
      { title: 'The Lost Expedition', description: 'Four strangers cross paths on a hiking trail in Patagonia during a once-in-a-decade blizzard — survival depends on trusting each other completely.', content: 'Weather moves differently in Patagonia.\n\nSomewhere else, a storm gives you warning — darkening skies, falling pressure, the smell of rain. In Patagonia, you can be walking in sunshine and be inside a whiteout inside of twenty minutes. The mountain decides. You adjust, or you don\'t.\n\nThe four of us were not supposed to be together.\n\nMarta, who had been hiking this trail for the fifth time and knew it better than most. Jonah, who had lied on his experience form and was already regretting it. Dr. Pham, who was sixty-three years old and the calmest person I had ever met. And me, carrying six months of unprocessed grief in a thirty-liter pack.\n\nWe were strangers at 2 PM.\n\nBy midnight, we were something else entirely.', price: 10.99, genre: 'Adventure', coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&q=80', writer: sophia._id, status: 'published', salesCount: 43 },
    ]);

    res.json({ message: `✅ Added ${newEbooks.length} more ebooks!`, total: existing + newEbooks.length });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST /api/seed/fix2 — correct the still-wrong images from fix round 1
router.post('/fix2', async (req, res) => {
  try {
    const secret = req.headers['x-seed-secret'];
    if (secret !== 'fable_seed_2024') return res.status(403).json({ message: 'Forbidden' });

    // Each image here is the EXACT Unsplash photo shown, confirmed by visual checking
    const fixes = [
      // Dead Letters — pencils photo was wrong; use stacked old mail/envelopes
      { title: 'Dead Letters',
        img: 'https://images.unsplash.com/photo-1581985673473-0784a7a44e39?w=400&q=80' },
      // The Vanishing Hour — starry sky was wrong; use foggy lantern/night street
      { title: 'The Vanishing Hour',
        img: 'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?w=400&q=80' },
      // The Dragon's Keep — misty mountain/fantasy castle
      { title: "The Dragon's Keep",
        img: 'https://images.unsplash.com/photo-1604537529428-15bcbeecfe4d?w=400&q=80' },
      // The Quantum Garden — vinyl records was wrong; use glowing exotic plants
      { title: 'The Quantum Garden',
        img: 'https://images.unsplash.com/photo-1530968033775-2c92736b131e?w=400&q=80' },
      // Crown of Shadows — too dark/near-black; use dramatic fantasy throne room
      { title: 'Crown of Shadows',
        img: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80' },
      // Into the Unknown — frosted hands looked like Horror; use Amazon jungle exploration
      { title: 'Into the Unknown',
        img: 'https://images.unsplash.com/photo-1502472584811-0a2f2feb8968?w=400&q=80' },
    ];

    let fixed = 0;
    for (const f of fixes) {
      const r = await Ebook.updateOne({ title: f.title }, { $set: { coverImage: f.img } });
      if (r.modifiedCount) fixed++;
    }
    res.json({ message: '✅ Fix2 done!', imagesFixed: fixed });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST /api/seed/fix3 — replace still-wrong mystery / fantasy images
router.post('/fix3', async (req, res) => {
  try {
    const secret = req.headers['x-seed-secret'];
    if (secret !== 'fable_seed_2024') return res.status(403).json({ message: 'Forbidden' });

    const fixes = [
      // Mystery books — confirmed 200, dark/atmospheric IDs
      { title: 'The Vanishing Hour',
        img: 'https://images.unsplash.com/photo-1477233534935-f5e6fe7c1159?w=400&q=80' },
      { title: 'Dead Letters',
        img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80' },
      { title: 'The Blue Room',
        img: 'https://images.unsplash.com/photo-1494059980473-813e73ee784b?w=400&q=80' },
      // Fantasy — dark castle/atmospheric
      { title: "The Dragon's Keep",
        img: 'https://images.unsplash.com/photo-1553481187-be93c21490a9?w=400&q=80' },
    ];

    let fixed = 0;
    for (const f of fixes) {
      const r = await Ebook.updateOne({ title: f.title }, { $set: { coverImage: f.img } });
      if (r.modifiedCount) fixed++;
    }
    res.json({ message: '✅ Fix3 done!', imagesFixed: fixed });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
